packages: []
catalogs:
  build:
    tsdown: ^0.20.3
  dev:
    bumpp: ^10.4.1
    pncat: ^0.10.0
    simple-git-hooks: ^2.13.1
    taze: ^19.9.2
    tsx: ^4.21.0
    typescript: ^5.9.3
  lint:
    '@octohash/eslint-config': ^0.2.2
    eslint: ^10.0.0
    lint-staged: ^16.2.7
  prod:
    '@clack/prompts': ^1.0.1
    ansis: ^4.2.0
    bottleneck: ^2.19.5
    cac: ^6.7.14
    ofetch: ^1.5.1
    p-retry: ^7.1.1
    pathe: ^2.0.3
    unconfig: ^7.4.2
    zod: ^4.3.6
  test:
    vitest: ^4.0.18
  types:
    '@types/node': ^24.10.13
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
